### ISSUE TITLE
Tokens do not leave wallet

### ISSUE THREAD

**Issue by imaginaryusername** [simpleledger/electrum#28]
Sent wallet, recipient got the 546sats UTXO but token balance didn't move on either side. Transaction:

https://blockchair.com/bitcoin-cash/transaction/13dd8ca58e99db059527a1cd6c26f864c42241c9ad1c72d39203899213f01188

token id: 04045592bddf759c2124f9c4fa23b1db50e9a40a58506e5589231e4d0cf23d1d

Sent with 3.4.1

**Comment by jcramer** [comment]
Please check settings “send only confirmed coins”, I had a similar issue yesterday after this sending was changed by the BFP code.


________________________________

**Comment by jcramer** [comment]
@imaginaryusername I think this latest commit should fix the problem for you.

**Comment by imaginaryusername** [comment]
Thanks for the fix, but I tried 3.4.2 with a git pull justnow and tokens are still not leaving my wallet and it did not show up in SLP history. Tried with "spend confirmed funds only" too. https://blockchair.com/bitcoin-cash/transaction/15d31a34df72c473ebd4e6b29b37e6b136fe8682acebf4a589b115829f71a49d

**Comment by jcramer** [comment]
If you take a look the token graph it shows two addresses should still be holding the tokens.  Block from 1 month ago, please check to see if these coins are in your wallet.

https://tokengraph.network/token/04045592bddf759c2124f9c4fa23b1db50e9a40a58506e5589231e4d0cf23d1d#tx=8844297e567661a2e08f1f734dc605c43dc6dc76886496fa827eeae9c1923eca

**Comment by jcramer** [comment]
I'm closing this issue, but we should continue the dialog here.  Issue #26 is open still, which is the root cause of the problems I believe.

@imaginaryusername are you at BCHdevcon?

**Comment by imaginaryusername** [comment]
Not at devcon. I checked and indeed bitcoincash:qz6nfq7qtwsnm8vytcr5t8hw4wajttmk0syxlcttge indicated in tokengraph is still in my wallet. The SLP wallet refuses to touch it though, how do I force it to use the output?

**Comment by imaginaryusername** [comment]
I think I finally got the mystery figured out - the token address was frozen in UI, so SLP omitted it from the tx when sending! 

Not sure how the freeze made it there - might be me messing with plugins elsewhere - but SLP should probably warn me that the token is not actually gonna be sent if the coin is frozen, instead of pretending to send it while nothing actually happens token-wise (while still generating a tx that pays fee). Would love to see the UI fixed to check that.

**Comment by jcramer** [comment]
What a relief!  I’m glad you noticed this, because I was scratching my head pretty hard. 😊
